include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # --- Error Rules ---
    - avoid_print: true
    - avoid_empty_else: true
    - avoid_relative_lib_imports: true
    - avoid_types_as_parameter_names: true
    - no_duplicate_case_values: true
    - prefer_void_to_null: true
    - unrelated_type_equality_checks: true

    # --- Style Rules ---
    - always_specify_types: false # Set to true if you want explicit types everywhere
    - camel_case_extensions: true
    - camel_case_types: true
    - library_names: true
    - library_prefixes: true
    - non_constant_identifier_names: true
    - prefer_const_constructors: true
    - prefer_const_constructors_in_immutables: true
    - prefer_const_declarations: true
    - prefer_const_literals_to_create_immutables: true
    - prefer_final_fields: true
    - prefer_final_locals: true
    - prefer_single_quotes: true
    - sort_child_properties_last: true
    - type_init_formals: true

    # --- Pub Rules ---
    - package_names: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
